// Generated by pnpm themes:generate.
import type {} from "uniwind/types";
declare module "uniwind" {
  export interface UniwindConfig {
    themes: readonly [
      "light",
      "dark",
      "library",
      "paper",
      "midnight",
      "forest",
      "tokyo-night",
      "catppuccin-frappe",
      "catppuccin-latte",
      "catppuccin-macchiato",
      "catppuccin-mocha",
      "dracula",
      "gruvbox-dark-hard",
      "nord",
    ];
  }
}
