"""Build a phone-friendly, offline screenshot journal. Serve only docs/ui-gallery."""
from pathlib import Path
import html
root=Path(__file__).resolve().parents[1]/'docs/ui-gallery'
cards=[]
for path in sorted(root.glob('*/*.png'),reverse=True):
    relative=path.relative_to(root).as_posix()
    before='before' in relative
    name=path.stem.replace('iphone-','').replace('-',' ').title()
    theme='catppuccin' if 'catppuccin' in path.name else 'before' if before else 'tokyo-night' if 'tokyo-night' in path.name else 'midnight' if 'midnight' in path.name else 'paper'
    stage='Community themes' if 'community' in relative else 'Initial version' if before else 'Refined version'
    cards.append(f'<article data-theme="{theme}"><a href="{html.escape(relative)}" target="_blank" aria-label="Open full screenshot: {html.escape(name)}"><img src="{html.escape(relative)}" loading="lazy" width="440" height="956" alt="{html.escape(name)} — actual iPhone simulator capture"></a><div class="caption"><span>{stage} · {path.parent.name[:10]}</span><h2>{html.escape(name)}</h2><a href="{html.escape(relative)}" download>Save original ↗</a></div></article>')
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>Glassleaf — iPhone gallery</title><style>
:root{font-family:system-ui,sans-serif;color:#202d27;background:#f4f5f1;--surface:#fff;--muted:#59655e;--line:#dce0d9;--accent:#285b43}*{box-sizing:border-box}body{margin:0}header,main{max-width:1260px;margin:auto;padding:28px 24px}header{padding-top:42px}header>p{max-width:690px;color:var(--muted);line-height:1.6}h1{font-size:clamp(28px,5vw,44px);letter-spacing:-1.5px;margin:12px 0}.brand{font-size:14px;font-weight:700;color:var(--accent)}nav{display:flex;gap:8px;flex-wrap:wrap;margin-top:24px}button{font:inherit;font-size:14px;border:1px solid var(--line);background:var(--surface);color:inherit;border-radius:999px;padding:11px 16px;cursor:pointer;min-height:44px}button[aria-pressed=true]{background:var(--accent);color:var(--surface);border-color:var(--accent)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:28px;align-items:start}article{background:var(--surface);border:1px solid var(--line);border-radius:20px;overflow:hidden}article img{display:block;width:100%;height:auto;aspect-ratio:440/956;object-fit:contain;background:var(--surface)}.caption{padding:18px}.caption span,.caption a{font-size:12px;color:var(--muted)}h2{font-size:17px;margin:8px 0 12px}.note{border-left:3px solid var(--accent);padding-left:16px;font-size:14px}a{color:var(--accent)}[hidden]{display:none!important}footer{padding:30px 24px;text-align:center;color:var(--muted);font-size:12px}@media(max-width:560px){header,main{padding:22px 16px}.grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}article{border-radius:12px}.caption{padding:12px}h2{font-size:14px}.caption span{font-size:10px}}@media(prefers-color-scheme:dark){:root{color:#c0caf5;background:#1a1b26;--surface:#24283b;--muted:#a9b1d6;--line:#3b4261;--accent:#7aa2f7}}
</style></head><body><header><div class="brand">GLASSLEAF / DESIGN JOURNAL</div><h1>Glassleaf on iPhone.</h1><p>Actual iPhone simulator captures, kept as a visual record as Glassleaf evolves. Choose a theme below, then tap any screen to inspect or save the full-resolution image.</p><p class="note">September 6, 2026 · iPhone 17 Pro Max. Sample books only. Theme switching and reader interactions are checked with native UI automation; see the <a href="validation.txt">validation notes</a> for exact coverage.</p><nav aria-label="Filter screenshots"><button data-filter="all" aria-pressed="true">All screens</button><button data-filter="paper" aria-pressed="false">Paper</button><button data-filter="tokyo-night" aria-pressed="false">Tokyo Night</button><button data-filter="midnight" aria-pressed="false">Midnight</button><button data-filter="catppuccin" aria-pressed="false">Catppuccin</button><button data-filter="before" aria-pressed="false">Before</button></nav></header><main class="grid">'''+''.join(cards)+'''</main><footer>Original captures are preserved. Gallery colors follow your phone’s light or dark appearance.</footer><script>document.querySelectorAll('button[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('button[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelectorAll('article').forEach(card=>card.hidden=button.dataset.filter!=='all'&&card.dataset.theme!==button.dataset.filter)}));</script></body></html>'''
(root/'index.html').write_text(page)
print(f'Gallery: {len(cards)} original captures')
