import { writeFile } from "node:fs/promises";
import { builtinThemes } from "../packages/ui/src/themeDefinition";
import { paletteVariables } from "../packages/ui/src/tokens";
const variants = [
  ["light", builtinThemes.find((theme) => theme.id === "paper")!],
  ["dark", builtinThemes.find((theme) => theme.id === "midnight")!],
  ["library", builtinThemes.find((theme) => theme.id === "forest")!],
  ...builtinThemes.map((theme) => [theme.id, theme] as const),
] as const;
const declarations = (colors: Parameters<typeof paletteVariables>[0]) =>
  Object.entries(paletteVariables(colors))
    .map(([key, value]) => `      ${key}: ${value};`)
    .join("\n");
const css = `/* Generated by pnpm themes:generate. Edit validated theme definitions. */\n@theme {\n  --font-sans: "DM";\n  --font-serif: "Lora";\n${declarations(variants[0][1].colors)}\n}\n@layer theme {\n  :root {\n${variants.map(([name, theme]) => `    @variant ${name} {\n${declarations(theme.colors)}\n    }`).join("\n")}\n  }\n}\n`;
await writeFile(new URL("../packages/ui/styles.css", import.meta.url), css);
await writeFile(
  new URL("../packages/ui/theme-names.json", import.meta.url),
  JSON.stringify(
    variants
      .map(([name]) => name)
      .filter((name) => name !== "light" && name !== "dark"),
    null,
    2,
  ) + "\n",
);
console.log(`Generated ${variants.length} theme variants.`);
