import { readFile, writeFile } from "node:fs/promises";
import { builtinThemes } from "../packages/ui/src/themeDefinition";
import { paletteVariables } from "../packages/ui/src/tokens";
const variants = [
  ["light", builtinThemes.find((theme) => theme.id === "paper")!],
  ["dark", builtinThemes.find((theme) => theme.id === "midnight")!],
  ["library", builtinThemes.find((theme) => theme.id === "forest")!],
  ...builtinThemes.map((theme) => [theme.id, theme] as const),
] as const;
const declarations = (colors: Parameters<typeof paletteVariables>[0]) =>
  Object.entries(paletteVariables(colors))
    .map(([key, value]) => `      ${key}: ${value};`)
    .join("\n");
const css = `/* Generated by pnpm themes:generate. Edit validated theme definitions. */\n@theme {\n  --font-sans: "DM";\n  --font-serif: "Lora";\n${declarations(variants[0][1].colors)}\n}\n@layer theme {\n  :root {\n${variants.map(([name, theme]) => `    @variant ${name} {\n${declarations(theme.colors)}\n    }`).join("\n")}\n  }\n}\n`;
const names =
  JSON.stringify(
    variants
      .map(([name]) => name)
      .filter((name) => name !== "light" && name !== "dark"),
    null,
    2,
  ) + "\n";
const registry = `// Generated by pnpm themes:generate.\nimport type {} from "uniwind/types";\ndeclare module "uniwind" {\n  export interface UniwindConfig {\n    themes: readonly [\n${variants.map(([name]) => `      ${JSON.stringify(name)},`).join("\n")}\n    ];\n  }\n}\n`;
for (const [path, content] of [
  ["../packages/ui/styles.css", css],
  ["../packages/ui/theme-names.json", names],
  ["../packages/ui/src/themeRegistry.d.ts", registry],
]) {
  const url = new URL(path!, import.meta.url);
  if (process.argv.includes("--check")) {
    if ((await readFile(url, "utf8")) !== content)
      throw new Error(`${path} is stale. Run pnpm themes:generate.`);
  } else await writeFile(url, content!);
}
console.log(
  `${process.argv.includes("--check") ? "Checked" : "Generated"} ${variants.length} theme variants.`,
);
